apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-kudos-dev
resources:
  # Core
  - externalsecrets.yaml
  - postgres.yaml
  - mailpit.yaml
  - app.yaml

  # SSO
  - securitypolicy.yaml
