{
 "title": "Envoy Gateway / Overview",
 "description": "A dashboard that monitors Envoy Gateway with a focus on Kubernetes objects and XDS updates. The dashboards were generated using [envoy-mixin](https://github.com/adinhodovic/envoy-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "custom",
  "community",
  "envoy",
  "envoy-mixin",
  "gateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(xds_snapshot_update_total{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(xds_snapshot_update_total{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(xds_snapshot_update_total{cluster=\"$cluster\", namespace=~\"$namespace\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Envoy XDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XDS Snapshot Update Rate by Status/NodeID",
   "type": "timeseries",
   "description": "The rate of XDS snapshot updates by status and node ID.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    xds_snapshot_update_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (status, nodeID)\n",
     "legendFormat": "{{ status }}/{{ nodeID }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Resource Apply Rate by Status/Kind",
   "type": "timeseries",
   "description": "The rate of resource apply operations by status and kind.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    resource_apply_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (status, kind)\n",
     "legendFormat": "{{ status }}/{{ kind }}"
    }
   ]
  },
  {
   "title": "Resource Apply Duration",
   "type": "timeseries",
   "description": "The duration of resource apply operations (P50 and P95).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      resource_apply_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      resource_apply_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Resource Delete Rate by Status/Kind",
   "type": "timeseries",
   "description": "The rate of resource delete operations by status and kind.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    resource_delete_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (status, kind)\n",
     "legendFormat": "{{ status }}/{{ kind }}"
    }
   ]
  },
  {
   "title": "Resource Delete Duration",
   "type": "timeseries",
   "description": "The duration of resource delete operations (P50 and P95).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      resource_delete_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      resource_delete_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Status Update Rate by Kind/Status",
   "type": "timeseries",
   "description": "The rate of status update operations by kind and status.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    status_update_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (kind, status)\n",
     "legendFormat": "{{ kind }}/{{ status }}"
    }
   ]
  },
  {
   "title": "Status Update Duration",
   "type": "timeseries",
   "description": "The duration of status update operations (P50 and P95).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      status_update_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      status_update_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}