{
 "title": "VolSync Dashboard",
 "description": "Provides a basic dashboard for VolSync (See Project https://github.com/backube/volsync).",
 "tags": [
  "volsync",
  "storage",
  "backups",
  "custom"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(volsync_volume_out_of_sync,obj_namespace)"
    }
   },
   { "name": "replicationDestName", "label": "ReplicationDestName", "query": "${VAR_REPLICATIONDESTNAME}" },
   {
    "name": "volsyncNamespace",
    "query": {
     "query": "label_values(volsync_sync_duration_seconds,namespace)"
    }
   },
   {
    "name": "volsyncPod",
    "query": {
     "query": "label_values(volsync_sync_duration_seconds,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Sources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volsync_replicationsource_info{obj_namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Run OK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volsync_replicationsource_info{obj_namespace=~\"$namespace\",latest_result=\"Successful\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Backups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volsync_missed_intervals_total{obj_namespace=~\"$namespace\",role=\"source\"} != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Never Backed Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(volsync_replicationsource_info{obj_namespace=~\"$namespace\",last_sync_time=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Duration",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volsync_sync_duration_seconds{obj_namespace=~\"$namespace\",obj_name!~\"$replicationDestName\",quantile=\"0.99\",role=\"source\"}",
     "legendFormat": "{{obj_name}}"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((kube_job_status_active{namespace=~\"$namespace\",job_name=~\"volsync-.*\"}) > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((kube_job_status_failed{namespace=~\"$namespace\",job_name=~\"volsync-.*\"}) > bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "volsync_replicationsource_info{obj_namespace=~\"$namespace\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Missed Backups",
   "type": "table",
   "description": "Number of times sync failed to complete before next scheduled start.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "volsync_missed_intervals_total{obj_namespace=~\"$namespace\",obj_name!~\"$replicationDestName\",role=\"source\"}!=0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Operational Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$volsyncPod\", namespace=~\"$volsyncNamespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$volsyncPod\", namespace=~\"$volsyncNamespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}