apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: sonarr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SONARR__AUTH__APIKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: sonarr-api-key
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: radarr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: radarr-api-key
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: prowlarr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PROWLARR__AUTH__APIKEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: prowlarr-api-key
        metadataPolicy: None
        nullBytePolicy: Ignore
