apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-media
resources:
  # Core
  - externalsecrets.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  - jellyfin.yaml
  - recyclarr.yaml

  # Storage
  - pv-media-nfs.yaml
  - volsync.yaml
