apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  disableNameSuffixHash: true
configMapGenerator:
  - name: authentik-blueprint-nextcloud
    namespace: apps
    files:
      - blueprints/nextcloud.yaml
resources:
  - backendtrafficpolicy.yaml
  - blueprint-immich-configmap.yaml
  - externalsecrets.yaml
  - networkpolicy.yaml
  - pvc-media.yaml
  - postgres.yaml
  - httproute.yaml
