apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-landing
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: landing-content
    files:
      - index.html
      - style.css
      - logos.css
      - logo.png
      - favicon.png
      - JetBrainsMono-Variable.woff2
      - IBMPlexSans-Regular.woff2
      - OFL.txt
resources:
  - app.yaml
  - backendtrafficpolicy.yaml
  - httproute.yaml
