apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ntfy-app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        auth-users: "andre:{{ .admin_password_hash }}:admin,homelab-bot:{{ .bot_password_hash }}:user"
        auth-access: "homelab-bot:homelab-*:wo"
        auth-tokens: "homelab-bot:{{ .alertmanager_token }}:alertmanager,homelab-bot:{{ .gatus_token }}:gatus,homelab-bot:{{ .argocd_token }}:argocd"
  data:
    - secretKey: admin_password_hash
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy-admin-password-hash
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: bot_password_hash
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy-bot-password-hash
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: alertmanager_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy-token-alertmanager
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: gatus_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy-token-gatus
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: argocd_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ntfy-token-argocd
        metadataPolicy: None
        nullBytePolicy: Ignore
