apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Core
  - application.yaml

  # Networking
  - clienttrafficpolicy.yaml
  - gateway.yaml

  # Metrics
  - metrics-servicemonitor.yaml
