apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-ai-web
resources:
  # Core
  - externalsecrets.yaml
  - searxng.yaml
  - playwright.yaml

  # Networking
  - networkpolicy.yaml
