apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: argocd
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-metrics
          - argocd-server-metrics
          - argocd-notifications-controller-metrics
          - argocd-applicationset-controller
          - argocd-repo-server
  endpoints:
    - port: metrics
      interval: 30s
