apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-diabeteshub
configMapGenerator:
  - name: diabeteshub-nginx
    files:
      - default.conf
resources:
  - app.yaml
  - networkpolicy.yaml
  - httproute.yaml
  - backendtrafficpolicy.yaml
